### ISSUE TITLE
Cannot listen to port anymore

### ISSUE THREAD

**Issue by MrLocuace** [ramachandran-lab/pong#10]
Dear Sahar,
I successfully ran pong in my local computer. However, when I run another pong process, I get a message saying that it cannot listen to the port anymore because it is already in use:

    Parsing input and generating cluster network graph
    Matching clusters within each K and finding representative runs
    For K=3, there is 1 mode across 1 run.
    For K=4, there is 1 mode across 1 run.
    For K=5, there is 1 mode across 1 run.
    Matching clusters across K
    Finding best alignment for all runs within and across K
    match time: 0.06s
    align time: 0.00s
    total time: 0.10s
    Traceback (most recent call last):
      File "/data/anaconda2/bin/pong", line 437, in <module>
        main()
      File "/data/anaconda2/bin/pong", line 281, in main
        app.listen(opts.port)
      File "/data/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 2042, in listen
        server.listen(port, address)
      File "/data/anaconda2/lib/python2.7/site-packages/tornado/tcpserver.py", line 143, in 
    listen
        sockets = bind_sockets(port, address=address)
      File "/data/anaconda2/lib/python2.7/site-packages/tornado/netutil.py", line 168, in 
    bind_sockets
        sock.bind(sockaddr)
      File "/data/anaconda2/lib/python2.7/socket.py", line 228, in meth
        return getattr(self._sock,name)(*args)
    socket.error: [Errno 98] Address already in use 

I have two questions:

1. How to solve this?. Is there any way to avoid manually specifying the port every time I run a pong process?
2. Can I run pong in a remote server so that it opens the web interfase directly, or I always need to run pong locally?

Thanks very much

**Comment by shahamat** [comment]
1) You will have to kill the process that is running pong so that you can start a new one with the same default address (`http://localhost:4000`). You can get the process ID (PID) of your previous pong run by looking for the command you used to run pong in the output of `ps -e`. And then you can kill that process by issuing the command `kill {PID}`, where PID is the process ID of pong.
2) Unfortunately pong is only set up to run locally.

Hope that helps!

**Comment by MrLocuace** [comment]
Thanks very much !!
