### ISSUE TITLE
Error parsing filemap:

### ISSUE THREAD

**Issue by zillurbmb51** [ramachandran-lab/pong#12]
Hello, I have admixture outputs which I want to plot using pong. My filemap are attached. No matter how I edit my filemap it always say that: 
`Error parsing filemap: check that the file is tab-delimited, that the columns are ordered properly, and that the '#' character is not used other than to indicate the start of a comment (i.e. it cannot be used as part of a runID).

[filemap13.txt](https://github.com/ramachandran-lab/pong/files/3642962/filemap13.txt)
[filemap15.txt](https://github.com/ramachandran-lab/pong/files/3642963/filemap15.txt)
`
Any help? Best, Zillur

**Comment by abehr** [comment]
Hi Zillur,

The _filemap_ must be a 3-column file; it looks like you have an extra column for line numbers, and an extra non-commented row for column headers. Based on the example _filemap_ depiction (Table 1 in the manual), I can see why this was confusing! I've attached a reformatted version of `filemap13.txt` that should work properly. You can also refer to the _filemap_ provided with the pong example dataset. Hope that helps!

[filemap13_reformatted.txt](https://github.com/ramachandran-lab/pong/files/3643039/filemap13_reformatted.txt)

Best,
Aaron

**Comment by zillurbmb51** [comment]
Ohh! I was thinking about this error type. Thank you. Now I am getting a new error:
```
(base) [zillur@dutillab captured_regions]$ pong -m filemap17 -i snps_plot/pops_all2 -o pong2

Output dir pong2 already exists.
Overwrite? (y/n): y

-------------------------------------------------------------------
                            p o n g
      by A. Behr, K. Liu, T. Devlin, G. Liu-Fang, and S. Ramachandran
                       Version 1.4.7 (2016)
-------------------------------------------------------------------
-------------------------------------------------------------------

Parsing input and generating cluster network graph
Error parsing filemap: encountered duplicate Q matrix ID s1321.

```
Any help? 
[filemap17.txt](https://github.com/ramachandran-lab/pong/files/3643167/filemap17.txt)

**Comment by abehr** [comment]
Each run (i.e. each _Q_-matrix generated by running Admixture) listed in your _filemap_ must be labeled with a unique runID. It looks like you have multiple runs in your _filemap_ with the same ID, which is why pong is giving that error message. For example, you could change the names of the first two runs in your _filemap_ to `s1321_K=1` and `s1321_K=9`. 

You can learn more about this in section 5.2 of the [pong manual](https://github.com/ramachandran-lab/pong/blob/master/pong-manual.pdf).

**Comment by zillurbmb51** [comment]
Thank you very much. It works now! I got the attached figure. Is there any way to customized order the plot (For example, in the attached figure at the top I have tcga_hg38_somatic; all test are not readable, I want this panel to the middle or bottom with full panel names).  
![modes_K=8_2019-8-30_10h17m15s_pong](https://user-images.githubusercontent.com/12833907/66662854-9766a400-ec17-11e9-959a-a6c81e3af8aa.png)

**Comment by abehr** [comment]
Modes are sorted by how many runs they represent, with the major mode appearing first. Unfortunately there's no way to specify a second sort order beyond this. However, you can remove any tests from your _filemap_ that are not necessary for analysis once you've identified as much, or you can download individual plots and then place them in any order.
