### ISSUE TITLE
Improve resolution of image

### ISSUE THREAD

**Issue by MrLocuace** [ramachandran-lab/pong#13]
Dear Sohini,
I want to include a pong image in a paper, but I am afraid the resolution I get from the image downloaded with the web tool is not the best. Is there any way to adjust the resolution of pong images?
Thanks very much

**Comment by sohinir** [comment]
Could you give us more information about how you're downloading the image?
An SVG or PDF (the PDF download is possible if you use the print icon and
then "Save to PDF" using your browser print method) should be very
high-res. We also have a slider for the download options that lets you set
the resolution for SVGs and PNGs.

**Comment by MrLocuace** [comment]
Dear Sohini,
thank you for your response. What I did is:
1. Run the pong command in my local server.
2. Go to http://localhost:4000/
3. A window pops up
