### ISSUE TITLE
trouble accessing results with http://localhost:4000

### ISSUE THREAD

**Issue by JenJen1984** [ramachandran-lab/pong#21]
Hello there, 
I am so looking forward to using Pong for my own data. 
Currently I am practising on the sample data however I cannot view the results after the pong server has started"running and listening on port 4000".
The http://localhost:4000 address doesn't work when I open my browser (I have tried chrome/firefox/safari) and it  says localhost refuses to connect . The command line stalls after telling me to open the web browser. Is there something different i could be doing to view the results? 

I apologise if this is a basic question, I am new to this and having asked at college, I have had no luck in solving my problem.
Many thanks for your time,
Jen

**Comment by sohinir** [comment]
This might be a cookie issue. Could you try opening an incognito browser window in Chrome (File > New Incognito Window) and then see if you can access http://localhost:4000?

**Comment by JenJen1984** [comment]
Thank you for getting back to me so quickly. Unfortunately, I reach the same error when using the incognito on chrome, or private window  in firefox. I have tried on a Mac  and a windows environment.

**Comment by shahamat** [comment]
Are you running pong locally or on a server?

**Comment by JenJen1984** [comment]
I am running Pong on a server ( my college's linux computing cluster).

**Comment by shahamat** [comment]
aha! so then localhost would also be the compute cluster and not your personal computer. A couple ways around this: (1) run pong on your personal computer. (2) see if your computing cluster has VNC servers set up, that way you can open up a browser on the server and then go to the localhost address. (3) look at this issue: https://github.com/ramachandran-lab/pong/issues/16

**Comment by JenJen1984** [comment]
Thank you so much for identifying the issue! I will ask at college tomorrow if a VNC is possible. I have tried setting up Pong locally on my macbook but homebrew would not support python2 for me just python 3.  I am looking at your Pong 3 release but my lack of python knowledge is hindering my installation abilities... I will keep trying!
 Thank you so much for your time.

**Comment by shahamat** [comment]
No problem! The third option might be the easiest one. You open two windows on your compute cluster. In one window, you run pong. and then you go to the other window and type `ssh -N -L 4000:localhost:4000 <remote cluster>`. and replace <remote cluster> with the address of your compute cluster. Then open a browser on your person computer and go to the localhost address. Good luck!
