### ISSUE TITLE
puzzled with the result of pong

### ISSUE THREAD

**Issue by kevinluoXiao** [ramachandran-lab/pong#25]
![截屏2022-07-26 10 06 09](https://user-images.githubusercontent.com/110002906/180906992-663c3835-a3a2-482d-824f-581d203fa0c3.png)
Hello!
    I have several results from Admixture for several K and 10 runs for each K. I'm successfully run pong, and get a directory containing results. But I just want to get a final result which only have one aligned Q matrix for each K , like the result of CLUMPP, and these Q matrixes are aligned across the K. I'm not sure whether I should choose one of the representative runs for each K to plot in R, because pong tell me there are several representative runs in some K. So I'm puzzled with the result of pong.
    Hoping for your help!
    Thanks.

**Comment by sohinir** [comment]
By representative runs, do you mean modes? It does appear you have multiple modes per K, each of which has multiple representative runs. Have you used pong's native visualization to see what the differences among modes are, before considering what to plot in R? I suggest doing that first and keeping us posted.

**Comment by kevinluoXiao** [comment]
Thanks for your concern!
    I get results from Admixture, which include a group containing 481 sample, and K=2~22. Then I use this command for pong "pong -v -m ./filemap.txt -i pop.txt -n pop_order.txt". Because of unknown population information, I classify the pop_info in "pop.txt" by sample ID. Then I sort sample according to "pop_order.txt" by the order from phylogeny tree. 
   Everything is OK! But when I open http://localhost:4000 in Safari, I staying on this page for 20 minutes and don't finish.

**Comment by kevinluoXiao** [comment]
Thanks for your concern!
    I get results from Admixture, which include a group containing 481 sample, and K=2~22. Then I use this command for pong "pong -v -m ./filemap.txt -i pop.txt -n pop_order.txt". Because of unknown population information, I classify the pop_info in "pop.txt" by sample ID. Then I sort sample according to "pop_order.txt" by the order from phylogeny tree. 
   Everything is OK! But when I open http://localhost:4000 in Safari, I staying on this page for 20 minutes and don't finish.

**Comment by kevinluoXiao** [comment]
> By representative runs, do you mean modes? It does appear you have multiple modes per K, each of which has multiple representative runs. Have you used pong's native visualization to see what the differences among modes are, before considering what to plot in R? I suggest doing that first and keeping us posted.

Thanks for your concern!
I get results from Admixture, which include a group containing 481 sample, and K=2~22. Then I use this command for pong "pong -v -m ./filemap.txt -i pop.txt -n pop_order.txt". Because of unknown population information, I classify the pop_info in "pop.txt" by sample ID. Then I sort sample according to "pop_order.txt" by the order from phylogeny tree.
Everything is OK! But when I open http://localhost:4000/ in Safari, I staying on this page for 20 minutes and don't finish.
![Uploading 截屏2022-07-29 15.42.37.png…]()

**Comment by kevinluoXiao** [comment]
Thanks for your concern!
I get results from Admixture, which include a group containing 481 sample, and K=2~22. Then I use this command for pong "pong -v -m ./filemap.txt -i pop.txt -n pop_order.txt". Because of unknown population information, I classify the pop_info in "pop.txt" by sample ID. Then I sort sample according to "pop_order.txt" by the order from phylogeny tree.

Everything is OK! But when I open http://localhost:4000/ in Safari, I staying on Progress Bars for 20+ minutes and don't finish.

Yeah, I just want to see the difference between representative runs for each K to choose the best final graph. But I guess maybe my data is too big for pong's native visualization. So, in this case, I just use the align result from pong and try to plot it in R.

**Comment by sohinir** [comment]
Hi - would you be willing to email us (contact emails are in this repo's README.md) a minimum working example - a subset of your files across K values so we can try to reconstruct the problem? I also suggest trying an incognito browser window in case some other processes are running or are cached on your computer. I also just want to make sure you're running pong locally as opposed to on a server (or on an interactive node so you can plot).

**Comment by abehr** [comment]
Closing this as stale for now. @kevinluoXiao - feel free to reopen if you would like to continue troubleshooting. Admixture results with 481 individuals at K=2~22 should not be a problem for pong's native visualization, so there is likely some other error occurring.
