### ISSUE TITLE
pong: Error parsing input file

### ISSUE THREAD

**Issue by yzliu01** [ramachandran-lab/pong#28]
Hi, my data generated by Admixture as input for pong caused the following problem. I did this visualization in the same way as before, which did not show this problem. The admixture .Q data is whitespace-separated.  It seems no similar issues are reported, and I could not figure out it. Can you please give me a hint?
```
Error parsing input file: could not convert Q matrix data entry to float.
Perhaps the value of `--ignore_columns` is incorrect or a file with a different format was included somewhere.
```

**Comment by yzliu01** [comment]
The problem that was due to fileMap issue is solved.

**Comment by abehr** [comment]
Sounds good! Let us know if you have any other issues.
