### ISSUE TITLE
List of default colors

### ISSUE THREAD

**Issue by MrLocuace** [ramachandran-lab/pong#29]
Hello
may I ask you to provide the list of the 26 default colors that you use for the plots?
Thank you

**Comment by abehr** [comment]
You can find it in here in the current repository:

https://github.com/ramachandran-lab/pong/blob/bd5f65a9904cabfff7cbeddaecd72875f1b2e5b2/static/pong.js#L56

**Comment by MrLocuace** [comment]
Perfect, thank you !!
