### ISSUE TITLE
Cannot open the http://localhost:4000/ in my web browser 

### ISSUE THREAD

**Issue by Crazzy-Rabbit** [ramachandran-lab/pong#30]
"Open your web browser and navigate to http://localhost:4000/ to see the visualization" But entering this URL in the browser will show access denied. How do I solve this problem

**Comment by shahamat** [comment]
Hi, are you running pong locally or on a server?

**Comment by Crazzy-Rabbit** [comment]
Thanks for your response. We use our lab server to run pong, and wang to visualize the result using local web browser.But it not success

**Comment by sohinir** [comment]
pong's front end needs direct access to the output files from its alignment process to produce the visualization. If you are not running pong locally, you'll need to ftp/copy the output directory to your local machine to produce the visualization. Or contact your local sysadmins to ask about whether there is an interactive node on your server in which you could produce the visualization. Please reopen if this does not solve your problem.
