### ISSUE TITLE
Error parsing input files: there must be at least one Q matrix for every K in [min_K, max_K]

### ISSUE THREAD

**Issue by lukaskon** [ramachandran-lab/pong#31]
Hello, I am running the following line and looking for advice:

```
pong -m Bcin123_LDsubset.Qfilemap -i Greenhouse.ind2pop -n pop_order.txt
```

I am getting the following error:
```
Error parsing input files: there must be at least one Q matrix for every K in [min_K, max_K]
```

I checked that the .Qfilemap is tab-delimited (pasted with spaces here):
```
A1      4       Bcin123_LDsubset.4.Q
B2      6       Bcin123_LDsubset.6.Q
C3      8       Bcin123_LDsubset.8.Q
D4      10     Bcin123_LDsubset.10.Q
```

Am I getting this error because I don't have 5.Q, 7.Q, etc? Is there no way around this?

**Comment by sohinir** [comment]
Yes - unfortunately we cannot align non-consecutive values of K in pong, because the method relies on comparing pairs of clusters for optimal alignment. It's not a feature we plan on building but if you find a method that does let us know!
