### ISSUE TITLE
error parsing ind2pop file

### ISSUE THREAD

**Issue by lcespedesarias** [ramachandran-lab/pong#35]
Hi!

I succesfully ran pong without the ind2pop file, but now that I am including population assignment information I get the following error: "Parsing input and generating cluster network graph/error: individual population file assignment contains more than 1 column of data". I believe that my file is formatted correctly: only has one column of three letter population codes. Is there any other potential problem that I am overlooking? Attached is the file.
 
[HZ.ind2pop.zip](https://github.com/user-attachments/files/18101539/HZ.ind2pop.zip)

Any insights are much appreciated.

Thanks so much!

Laura

**Comment by sohinir** [comment]
Hi! Thanks for using pong! Your file is formatted correctly when I unzip
it. Are you using the zipped file in your command line? If not, you could
send me a minimum working example at ***@***.*** and I can dig
into it further.

**Comment by lcespedesarias** [comment]
Thank you so much! I sent you an email. And to answer your question, I was using the unzipped version of the file when running pong (just zipped it to attach here). Thank you!

**Comment by sohinir** [comment]
I'm sorry the error is not more clear but, from the MWE you sent me, the
ind2pop file you are using is a different length than the number of rows in
your Q matrices. Your Q matrices all have 121 individuals but your ind2pop
file has 123 individuals. If you construct the correct length ind2pop
file, pong will run (as I observed from a test I did).

Good luck and enjoy using pong!

**Comment by lcespedesarias** [comment]
thank you so much! I fixed the error when building the ind2pop and now it works (the issue was that I needed to exclude some individuals from my original data that I dropped for the admixture runs, not really an issue with pong or admixture)
