### ISSUE TITLE
Integrating boostrapping files from ADMIXTURE

### ISSUE THREAD

**Issue by nehasavant** [ramachandran-lab/pong#4]
Hello! 

I am using pong to visualize my ADMIXTURE Q-files, but I'm confused on one part. I used a bootstrapping method  while running ADMXITURE (included the -B flag with 200 replicates) and for each K the output consisted of one Q file, one P file, one .se file and one .bias file. I don't have separate Q files for each "run" (i.e. I only have a single Q file for each k: k2r1, k3r1, k4r1) while the sample data set shows multiple Qs per k (i.e. k2r1, k2r2, k2r3, and k3r1, k3r2, k3r3, etc..)

Is there a different way you conducted "runs" in ADMIXTURE? 

Would appreciate any and all guidance, thanks!

**Comment by abehr** [comment]
Hi Neha,

Great question! To generate multiple _Q_-files per _K_ we actually run ADMIXTURE multiple times for each value of _K_. This is not strictly necessary -- you should still be able to use pong to visualize and analyze your existing data.

The reason it can be useful to generate replicate runs per _K_ is to assess the robustness of the clusters inferred at each value of _K_. The stochasticity of ADMIXTURE's clustering approach means that replicate runs can produce distinct solutions even when the same initial conditions are used. These distinct solutions can result from real biological factors, and we refer to this concept as _multimodality_ ([Jakobsson and Rosenberg, 2007](https://academic.oup.com/bioinformatics/article/23/14/1801/188285); [Behr _et al._, 2016](https://academic.oup.com/bioinformatics/article/32/18/2817/1744074)).

Hope this helps. Feel free to reach out if you have any other questions!
