### ISSUE TITLE
Visualize subsets of individuals

### ISSUE THREAD

**Issue by jhmarcus** [ramachandran-lab/pong#6]
Thank you for an incredibly useful and well developed tool! I have been running `ADMIXTURE` on 1000s of individuals, so the barplots can get unwieldy to see who is who. I would like to make a `PONG` visualization on a subset of individuals from the large Q matrix. Currently I just write a new Q matrix for the subset I want to visualize but I was wondering if there is a way to do this in `PONG` without having to write new files? Thanks!

**Comment by shahamat** [comment]
Hi! This functionality isn't current available, given that the alignment of matrices (across different modes and K values) needs all individuals. But if you want to talk further about this use case, we would love to hear more and see if we should push it up our queue to implement.

**Comment by abehr** [comment]
Hi Joseph - Thanks for the feedback.

As Sahar mentioned, the only way to truly generate a new visualization on a subset of indididuals in pong is to generate a new _Q_-matrix, as you've been doing. However, pong has a couple features that do allow you to approximate this functionality from within the interactive visualization.

If the individuals in your data are organized into populations (i.e. you have provided `-i/--ind2pop` and optionally `-n/--pop_names` inputs), you can highlight a subset of individuals that comprise a population by clicking on the population labels. You can select multiple populations by holding down the shift key. You can also zoom in on these individuals by hovering over a visualization and scrolling. You can even save/print the individual or composite barplots in this highlighted/zoomed state.

Hope this helps!

**Comment by jhmarcus** [comment]
Hey @shahamat and @abehr thank you for the thoughtful replies. Makes sense. I'll give the highlighting feature a try!
