### ISSUE TITLE
"Mean of empty slice" error?

### ISSUE THREAD

**Issue by zyxplus** [ramachandran-lab/pong#8]
/Users/pc/miniconda3/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/pc/miniconda3/lib/python2.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
 ret = ret.dtype.type(ret / rcount)
/Users/pc/miniconda3/lib/python2.7/site-packages/numpy/lib/function_base.py:356: RuntimeWarning: Mean of empty slice.

I can run pong successfully with the whole dataset, but the graph contains too many barplots,  so I extract a part of the data and rerun it, then error above happens, through it also shows information to remind me of checking the visualization, but I open the localhost, and the pong bar is empty for ten minutes...Seems that It won't give any result... Any suggestion?

**Comment by abehr** [comment]
We haven't seen this issue before, so I'd be interested to look into it. If your dataset isn't private, would you mind sharing it (either here or emailed to aaron_behr@alumni.brown.edu) -- we can try to figure out what's going on.

**Comment by zyxplus** [comment]
the e-mail address above rejected my e-mail twice.....
[testset.tar.gz](https://github.com/ramachandran-lab/pong/files/2986720/testset.tar.gz)

**Comment by hanyng** [comment]
I am encountering the same errors and the pong bar remains empty. If a solution was found I would be interested in seeing it. 

/sw/comp/python/2.7.11_milou/lib/python2.7/site-packages/numpy-1.12.0b1-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/sw/comp/python/2.7.11_milou/lib/python2.7/site-packages/numpy-1.12.0b1-py2.7-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/sw/comp/python/2.7.11_milou/lib/python2.7/site-packages/numpy-1.12.0b1-py2.7-linux-x86_64.egg/numpy/lib/function_base.py:1110: RuntimeWarning: Mean of empty slice.

**Comment by sohinir** [comment]
> the e-mail address above rejected my e-mail twice.....
> [testset.tar.gz](https://github.com/ramachandran-lab/pong/files/2986720/testset.tar.gz)

@zyxplus, your pop_names file plot_pop_names_1_1.list maps the code MY-TM to two different population names:
MY-TM	Kampung_Parit_Gong
MY-TM	Temuan

When I remove one of these lines, I can produce the bar plots. Would you respond regarding whether this fixed your issue?

**Comment by hanyng** [comment]
I tried it before and after removing one of the  MY-TM Kampung_Parit_Gong
and MY-TM Temuan and it solved the problem. I will try and see if there are
duplicates in my pop_order file as it seems the problem was my files. If it
for whatever reason does not work and I can see why I will contact again.
Thanks alot for the help!
/ Hannes

Den ons 27 mars 2019 kl 15:48 skrev Sohini Ramachandran <
notifications@github.com>:

**Comment by abehr** [comment]
We'll publish an update to pong soon with better input validation to prevent this error from showing up. Meanwhile, let us know if run into any other issues.

**Comment by abehr** [comment]
This issue is resolved in v1.4.9
