### ISSUE TITLE
Error parsing filemap

### ISSUE THREAD

**Issue by MrLocuace** [ramachandran-lab/pong#9]
Hello, I am trying to run pong in a remote server as well as on my local macbook. 

I have a Q matrix that looks like this:

    9.6869531197339453e-01 7.0001612683144405e-03 2.4304526758291086e-02
    9.1670413452871935e-01 2.4592171582268924e-02 5.8703693889011845e-02
    9.6442301916821649e-01 1.8636979112733810e-02 1.6940001719049826e-02
    9.3707495021816334e-01 2.3136152660889114e-02 3.9788897120947617e-02
    9.3633009044797855e-01 2.9465187961436479e-02 3.4204721590584901e-02

a tab-delimited filemap like this:

    k3    3    /data/path/my_k3_Q.matrix

and an ind2pop file like this:

    EUR
    EUR
    EUR
    EUR
    EUR

When I run the following command line:

    pong --filemap /data/path/my_filemap.txt  --col_delim "\t" \
         --ind2pop /data/path/my_ind2pop.txt

I get: 

    Parsing input and generating cluster network graph
    Error parsing filemap: check that the file is tab-delimited, that the columns are ordered 
    properly, and that the '#' character is not used other than to indicate the start of a comment 
    (i.e. it cannot be used as part of a runID).

I am struggling to find my error both in linux and mac, but I am not able to do it

Any suggestion would be highly welcome. Thanks a lot

**Comment by shahamat** [comment]
Hi,

From the filemap that you posted here, it seems like it is not tab-delimited. Not sure if formatting was lost during copy/paste. But when I create a new filemap that is tab-delimited, I am able to get this running. I have attached a new filemap. Let me know if that solves the problem!

Best,
Sahar
[my_filemap.txt](https://github.com/ramachandran-lab/pong/files/3482427/my_filemap.txt)

**Comment by shahamat** [comment]
Oh and one more thing, I would get rid of the flag `--col_delim "\t"` since that refers to the delimiter of your Q matrix file, and not the filemap.

**Comment by MrLocuace** [comment]
It worked now ! Thanks so much, Sahar !
